"""remove number of students column

Revision ID: 0228c7cae29d
Revises: e2641b8781d6
Create Date: 2024-07-06 18:58:09.009815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0228c7cae29d'
down_revision: Union[str, None] = 'e2641b8781d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'number_of_student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('number_of_student', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
