"""added indexing to student ID

Revision ID: 0a13839505aa
Revises: 0228c7cae29d
Create Date: 2024-09-15 03:35:56.392655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a13839505aa'
down_revision: Union[str, None] = '0228c7cae29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    op.drop_index('ix_students_id', table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_students_id', 'students', ['id'], unique=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
