"""initial migration

Revision ID: e2641b8781d6
Revises: 540adda11bf1
Create Date: 2024-07-06 18:19:01.336696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2641b8781d6'
down_revision: Union[str, None] = '540adda11bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('number_of_student', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'number_of_student')
    # ### end Alembic commands ###
